authorName: default
experimentName: example_mnist_pytorch
trialConcurrency: 1
maxExecDuration: 50h
maxTrialNum: 40
#choice: local, remote, pai
trainingServicePlatform: remote
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 train.py
  codeDir: .
  gpuNum: 1
#machineList can be empty if the platform is local
machineList:
  - ip: 101.101.216.46
    port : 2222
    username: root
    sshKeyPath: /opt/ml/key
    # Below are examples of specifying python environment.
    # pythonPath: /opt/python3.7/bin
    # pythonPath: C:/Python37
    # Below is an example of specifying python environment for windows anaconda user. Multiple paths separated by ';'. 
    # pythonPath: C:/Users/yourname/.conda/envs/myenv;C:/Users/yourname/.conda/envs/myenv/Scripts;C:/Users/yourname/.conda/envs/myenv/Library/bin
    pythonPath: /opt/conda/bin/python
